id: IA7994922
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T05:03:33+00:00'
last_modified: '2022-06-07T22:17:21.112223+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22942
  title: བླ་ནག་པ་སྤུན་གསུམ་གྱི་མནོ་བསམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    D96D:
      image_group_id: I1KG22975
      title: ''
      total_pages: 254
      order: 1
      base_file: D96D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
